<script lang="ts">
  import { ArrowLeftRight, BarChart3, BriefcaseBusiness, LayoutDashboard, LogOut, Settings2, Target, TrendingUp, WalletCards } from 'lucide-svelte';
  import InvestmentNav from '$lib/components/InvestmentNav.svelte';
  import type { ActionData, PageData } from './$types';
  let { data, form }: { data: PageData; form: ActionData } = $props();
  let newAccountKind = $state('stocks');
  const money = (amount: number, currency: string) => `${currency === 'USD' ? '$' : 'ZiG '}${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
</script>
<svelte:head><title>Investment accounts — Budget</title></svelte:head>
<div class="app-frame"><aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link active" href="/investments"><TrendingUp size={18}/> Investments</a><a class="side-link" href="/budgets"><Target size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
<main class="main-area"><header class="topbar"><div><p class="date-label">Set up the accounts you invest through</p><p class="topbar-title">Investment accounts</p></div></header><InvestmentNav active="accounts"/><div class="content-wrap investment-content">
  <section class="welcome-row"><div><p class="eyebrow">Account setup</p><h1>Accounts<span class="accent-period">.</span></h1><p class="welcome-copy">Add accounts you already use. The opening amount records capital already held and does not move money from a personal wallet.</p></div></section>
  {#if data.loadError}<div class="setup-banner"><div><strong>Investment data is not ready</strong><p>{data.loadError}. Apply the investments migration in Supabase, then refresh.</p></div></div>{/if}{#if form?.message}<p class="form-alert" role="alert">{form.message}</p>{/if}
  <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">New account</p><h2>Create an investment account</h2><p class="section-caption">Stocks accounts track VFEX counters and brokerage cash. Forex accounts track daily equity.</p></div></div><form method="POST" action="?/createAccount" class="feature-form investment-form">
    <label>Account name<input name="name" maxlength="80" placeholder="VFEX brokerage or Forex account" required/></label><label>Type<select name="kind" bind:value={newAccountKind}><option value="stocks">Stocks · VFEX</option><option value="forex">Forex trading</option></select></label><label>Currency<select name="currency"><option value="USD">USD</option><option value="ZIG">ZiG</option></select></label><label>{newAccountKind === 'stocks' ? 'Broker cash already held' : 'Starting forex account equity'}<input name="initial_capital" type="number" min="0" step="0.01" value="0" inputmode="decimal"/></label><div class="form-wide form-footer"><p>This is an opening amount, not a new transfer. Add existing shares with their buy price on the Stocks page.</p><button class="primary-button" type="submit"><BriefcaseBusiness size={17}/> Create account</button></div>
  </form></section>
  <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Your accounts</p><h2>Account balances</h2></div></div>{#if data.accounts.length}<div class="investment-account-grid">{#each data.accounts as account}<article class="investment-account-card" class:forex-account-card={account.kind === 'forex'}><div class="investment-card-head"><span class="investment-kind">{account.kind === 'stocks' ? 'Stocks · VFEX' : 'Forex trading'}</span><span class="currency-badge" class:zig-badge={account.currency === 'ZIG'}>{account.currency === 'USD' ? 'USD' : 'ZiG'}</span></div><h2>{account.name}</h2><p class="investment-total">{money(account.totalValue, account.currency)}</p><p class="investment-total-caption">Current recorded value</p><div class="investment-card-stats"><div><span>{account.kind === 'stocks' ? 'Opening brokerage cash' : 'Starting forex equity'}</span><strong>{money(Number(account.opening_capital ?? 0), account.currency)}</strong></div><div><span>Net capital tracked</span><strong>{money(account.netContribution, account.currency)}</strong></div><div><span>Profit / loss</span><strong class:gain={account.gain >= 0} class:loss={account.gain < 0}>{money(account.gain, account.currency)}</strong></div></div><form method="POST" action="?/updateOpeningCapital" class="opening-capital-form"><input type="hidden" name="investment_account_id" value={account.id}/><label>{account.kind === 'stocks' ? 'Set brokerage cash balance' : 'Set starting forex equity'}<input name="opening_capital" type="number" min="0" step="0.01" value={account.opening_capital ?? '0'} required/></label><button class="secondary-button" type="submit">Save opening amount</button><small>Opening amounts do not affect personal wallets.</small></form></article>{/each}</div>{:else}<p class="investment-table-empty">No investment accounts yet.</p>{/if}</section>
  <footer class="dashboard-footer"><span>USD and ZiG remain separate.</span><span>Manage counters on Stocks and daily account values on Forex.</span></footer>
</div></main><nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a class="mobile-nav-active" href="/investments"><TrendingUp size={18}/><span>Investments</span></a><a href="/budgets"><Target size={18}/><span>Budgets</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav></div>
