<script lang="ts">
  import { ArrowLeftRight, BarChart3, CircleDollarSign, LayoutDashboard, LogOut, Settings2, Target, TrendingUp, WalletCards } from 'lucide-svelte';
  import InvestmentNav from '$lib/components/InvestmentNav.svelte';
  import { enhance } from '$app/forms';
  import { handleInvestmentSubmit } from '$lib/investments/feedback';
  import type { ActionData, PageData } from './$types';
  let { data, form }: { data: PageData; form: ActionData } = $props();
  const accounts = $derived(data.accounts.filter((account: any) => account.kind === 'forex'));
  const money = (value: number | string, currency: string) => `${currency === 'USD' ? '$' : 'ZiG '}${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
</script>
<svelte:head><title>Forex — Budget</title></svelte:head>
<div class="app-frame"><aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link active" href="/investments"><TrendingUp size={18}/> Investments</a><a class="side-link" href="/budgets"><Target size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
<main class="main-area"><header class="topbar"><div><p class="date-label">Daily account equity tracking</p><p class="topbar-title">Forex</p></div></header><InvestmentNav active="forex"/><div class="content-wrap investment-content">
  <section class="welcome-row"><div><p class="eyebrow">Trading journal</p><h1>Forex<span class="accent-period">.</span></h1><p class="welcome-copy">Record account equity after trading and after any deposits or withdrawals for the day.</p></div></section>
  {#if data.loadError}<div class="setup-banner"><div><strong>Investment data is not ready</strong><p>{data.loadError}. Apply the investments migration in Supabase, then refresh.</p></div></div>{/if}{#if form?.message}<p class="form-alert" role="alert">{form.message}</p>{/if}
  {#if accounts.length}<section class="investment-account-grid">{#each accounts as account}<article class="investment-account-card forex-account-card"><div class="investment-card-head"><span class="investment-icon"><CircleDollarSign size={18}/></span><span class="investment-kind">Forex trading account</span><span class="currency-badge" class:zig-badge={account.currency === 'ZIG'}>{account.currency === 'USD' ? 'USD' : 'ZiG'}</span></div><h2>{account.name}</h2><p class="investment-total">{money(account.totalValue, account.currency)}</p><p class="investment-total-caption">{account.latestValuation ? `Latest value · ${account.latestValuation.valuation_date}` : 'No daily value recorded yet'}</p><div class="investment-card-stats"><div><span>Net capital contributed</span><strong>{money(account.netContribution, account.currency)}</strong></div><div><span>Profit / loss</span><strong class:gain={account.gain >= 0} class:loss={account.gain < 0}>{money(account.gain, account.currency)}</strong></div><div><span>Return on net capital</span><strong class:gain={account.returnPercent !== null && account.returnPercent >= 0} class:loss={account.returnPercent !== null && account.returnPercent < 0}>{account.returnPercent === null ? '—' : `${account.returnPercent.toFixed(2)}%`}</strong></div></div></article>{/each}</section>
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">End of day</p><h2>Record closing equity</h2><p class="section-caption">Enter total broker equity, including open positions. Save again for the same date to update it.</p></div></div><form method="POST" action="?/valuation" class="feature-form investment-form compact-investment-form" use:enhance={handleInvestmentSubmit}><label>Forex account<select name="investment_account_id" required>{#each accounts as account}<option value={account.id}>{account.name} · {account.currency === 'USD' ? 'USD' : 'ZiG'}</option>{/each}</select></label><label>Closing equity<input name="closing_equity" type="number" min="0" step="0.01" inputmode="decimal" required/></label><label>Date<input name="valuation_date" type="date" value={data.today} required/></label><label class="form-wide">Daily note<input name="note" maxlength="240" placeholder="Optional note about the day"/></label><div class="form-wide form-footer"><p>Record after trading and any cash movements for the day.</p><button class="primary-button" type="submit">Save daily equity</button></div></form></section>
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Daily history</p><h2>Closing values</h2></div></div><div class="investment-activity-list">{#each data.valuations as valuation}<div class="investment-activity-row"><span class="investment-activity-icon"><TrendingUp size={16}/></span><div class="investment-activity-main"><strong>{accounts.find((account: any) => account.id === valuation.investment_account_id)?.name ?? 'Forex account'}</strong><span>{valuation.valuation_date}{valuation.note ? ` · ${valuation.note}` : ''}</span></div><strong class="investment-activity-amount">{money(valuation.closing_equity, accounts.find((account: any) => account.id === valuation.investment_account_id)?.currency ?? 'USD')}</strong></div>{:else}<p class="investment-table-empty">No daily closing equity recorded yet.</p>{/each}</div></section>
  {:else}<section class="investment-empty"><span class="investment-icon"><CircleDollarSign size={20}/></span><div><h2>Create a forex account first</h2><p>Add your forex trading account and starting capital on the Accounts page.</p><a class="primary-button compact-button" href="/investments/accounts">Open Accounts</a></div></section>{/if}
  <footer class="dashboard-footer"><span>Daily gain or loss adjusts for recorded deposits and withdrawals.</span><span>This journal tracks account value; it does not analyze individual currency trades.</span></footer>
</div></main><nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a class="mobile-nav-active" href="/investments"><TrendingUp size={18}/><span>Investments</span></a><a href="/budgets"><Target size={18}/><span>Budgets</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav></div>
