<script lang="ts">
  import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, BarChart3, BriefcaseBusiness, CircleDollarSign, LayoutDashboard, LogOut, Settings2, Target, TrendingUp, WalletCards } from 'lucide-svelte';
  import InvestmentNav from '$lib/components/InvestmentNav.svelte';
  import type { PageData } from './$types';
  let { data }: { data: PageData } = $props();
  const money = (value: number | string, currency: string) => `${currency === 'USD' ? '$' : 'ZiG '}${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const currencyLabel = (currency: string) => currency === 'USD' ? 'USD' : 'ZiG';
  function chartPoints(values: number[]) {
    if (values.length < 2) return '';
    const low = Math.min(...values); const high = Math.max(...values); const spread = high - low || 1;
    return values.map((value, i) => `${(i / (values.length - 1) * 160).toFixed(1)},${(34 - (value - low) / spread * 28).toFixed(1)}`).join(' ');
  }
  const forexChart = (id: string) => chartPoints(data.valuations.filter((row) => row.investment_account_id === id).slice(0, 14).reverse().map((row) => Number(row.closing_equity)));
</script>

<svelte:head><title>Investments — Budget</title></svelte:head>
<div class="app-frame">
  <aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link active" href="/investments"><TrendingUp size={18}/> Investments</a><a class="side-link" href="/budgets"><Target size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
  <main class="main-area">
    <header class="topbar"><div><p class="date-label">Long-term holdings and trading</p><p class="topbar-title">Investments</p></div></header>
    <InvestmentNav active="overview" />
    <div class="content-wrap investment-content">
      <section class="welcome-row"><div><p class="eyebrow">Portfolio journal</p><h1>Investment overview<span class="accent-period">.</span></h1><p class="welcome-copy">See your current account values, contributions, returns, and recent activity. Shares without a recorded closing price are carried at purchase cost until you enter a market close.</p></div></section>
      {#if data.loadError}<div class="setup-banner"><div><strong>Investment data is not ready</strong><p>{data.loadError}. Apply the investments migration in Supabase, then refresh.</p></div></div>{/if}
      {#if data.accounts.length}
        <section class="investment-account-grid" aria-label="Investment accounts">{#each data.accounts as account}
          <article class="investment-account-card" class:forex-account-card={account.kind === 'forex'}>
            <div class="investment-card-head"><span class="investment-icon">{#if account.kind === 'stocks'}<BriefcaseBusiness size={18}/>{:else}<CircleDollarSign size={18}/>{/if}</span><span class="investment-kind">{account.kind === 'stocks' ? 'Stocks · VFEX' : 'Forex trading'}</span><span class="currency-badge" class:zig-badge={account.currency === 'ZIG'}>{currencyLabel(account.currency)}</span></div>
            <h2>{account.name}</h2><p class="investment-total">{money(account.totalValue, account.currency)}</p><p class="investment-total-caption">{account.kind === 'stocks' ? (account.valuationPending ? 'Includes unpriced shares at recorded cost' : 'Broker cash + priced holdings') : `Latest closing equity${account.latestValuation ? ` · ${account.latestValuation.valuation_date}` : ''}`}</p>
            <div class="investment-card-stats"><div><span>Net contributions</span><strong>{money(account.netContribution, account.currency)}</strong></div><div><span>Profit / loss</span><strong class:gain={!account.valuationPending && account.gain >= 0} class:loss={!account.valuationPending && account.gain < 0}>{account.valuationPending ? 'Awaiting closing prices' : money(account.gain, account.currency)}</strong></div><div><span>Return on net capital</span><strong class:gain={!account.valuationPending && account.returnPercent !== null && account.returnPercent >= 0} class:loss={!account.valuationPending && account.returnPercent !== null && account.returnPercent < 0}>{account.valuationPending ? 'Awaiting prices' : account.returnPercent === null ? '—' : `${account.returnPercent.toFixed(2)}%`}</strong></div>{#if account.kind === 'stocks'}<div><span>Broker cash</span><strong>{money(account.currentCash, account.currency)}</strong></div>{#if account.unpricedPositionCost > 0}<div><span>Unpriced shares · carried at cost</span><strong>{money(account.unpricedPositionCost, account.currency)}</strong></div>{/if}<div><span>Unrealized gain on priced counters</span><strong class:gain={account.positions.some((position: any) => position.marketValue !== null) && account.stockUnrealized >= 0} class:loss={account.positions.some((position: any) => position.marketValue !== null) && account.stockUnrealized < 0}>{account.positions.some((position: any) => position.marketValue !== null) ? money(account.stockUnrealized, account.currency) : 'Awaiting prices'}</strong></div>{/if}</div>
            {#if account.kind === 'stocks'}<div class="investment-mini-list">{#each account.positions as position}<div><span><strong>{position.ticker}</strong> · {position.company_name}<small>{Number(position.shares).toLocaleString()} shares{position.quoteDate ? ` · close ${position.quoteDate}` : position.marketValue === null ? ` · awaiting close; carried at cost ${money(position.costBasis, account.currency)}` : ''}</small></span><strong>{position.marketValue === null ? 'At cost' : money(position.marketValue, account.currency)}</strong></div>{:else}<p class="investment-empty-line">Add a counter and record a first buy from the Stocks page.</p>{/each}</div>{:else if forexChart(account.id)}<div class="investment-sparkline"><span>Closing equity history</span><svg viewBox="0 0 160 40" role="img" aria-label="Forex closing equity trend"><polyline points={forexChart(account.id)} /></svg></div>{/if}
          </article>
        {/each}</section>
      {:else}<section class="investment-empty"><span class="investment-icon"><TrendingUp size={20}/></span><div><h2>Create your first investment account</h2><p>Start with a VFEX brokerage or forex account. You can add opening capital from the Accounts page.</p><a class="primary-button compact-button" href="/investments/accounts">Set up account</a></div></section>{/if}
      <section class="investment-quicklinks"><a href="/investments/accounts"><BriefcaseBusiness size={17}/><span><strong>Accounts</strong><small>Create or review your investment accounts</small></span><span>Open →</span></a><a href="/investments/stocks"><TrendingUp size={17}/><span><strong>Stocks</strong><small>Manage counters, trades, and daily prices</small></span><span>Open →</span></a><a href="/investments/forex"><CircleDollarSign size={17}/><span><strong>Forex</strong><small>Record daily closing equity</small></span><span>Open →</span></a><a href="/investments/transfers"><ArrowLeftRight size={17}/><span><strong>Transfers</strong><small>Deposit or withdraw investment capital</small></span><span>Open →</span></a></section>
      {#if data.accounts.length}<section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Recent activity</p><h2>Investment history</h2></div></div><div class="investment-activity-list">
        {#each [...data.trades.map((row: any) => ({ ...row, activityType: 'trade' })), ...data.movements.map((row: any) => ({ ...row, activityType: 'movement' })), ...data.valuations.map((row: any) => ({ ...row, activityType: 'valuation' }))].sort((a: any, b: any) => String(b.occurred_at ?? b.valuation_date).localeCompare(String(a.occurred_at ?? a.valuation_date))).slice(0, 12) as row}
          <div class="investment-activity-row"><span class="investment-activity-icon">{#if row.activityType === 'trade'}<ArrowLeftRight size={16}/>{:else if row.activityType === 'movement'}{#if row.kind === 'deposit'}<ArrowDownLeft size={16}/>{:else}<ArrowUpRight size={16}/>{/if}{:else}<TrendingUp size={16}/>{/if}</span><div class="investment-activity-main"><strong>{#if row.activityType === 'trade'}{row.kind === 'buy' ? 'Buy' : 'Sell'} · {data.counters.find((counter) => counter.id === row.counter_id)?.ticker ?? 'Counter'}{:else if row.activityType === 'movement'}{row.kind === 'deposit' ? 'Capital deposited' : 'Withdrawal'} · {data.accounts.find((account) => account.id === row.investment_account_id)?.name ?? 'Investment account'}{:else}Forex closing equity · {data.accounts.find((account) => account.id === row.investment_account_id)?.name ?? 'Forex account'}{/if}</strong><span>{row.occurred_at ? new Date(row.occurred_at).toLocaleDateString() : row.valuation_date}</span></div></div>
        {:else}<p class="investment-table-empty">Your investment activity will appear here.</p>{/each}
      </div></section>{/if}
      <footer class="dashboard-footer"><span>Values are entered manually and shown by account currency.</span><span>Stock prices and forex equity stay separate from household income and spending.</span></footer>
    </div>
  </main>
  <nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a class="mobile-nav-active" href="/investments"><TrendingUp size={18}/><span>Investments</span></a><a href="/budgets"><Target size={18}/><span>Budgets</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav>
</div>
