<script lang="ts">
  import { ArrowLeftRight, BarChart3, LayoutDashboard, LogOut, Plus, Settings2, WalletCards, ArrowDownLeft, ArrowUpRight } from 'lucide-svelte';
  import { enhance } from '$app/forms';
  import { handleInvestmentSubmit } from '$lib/investments/feedback';
  import type { PageData, ActionData } from './$types';
  let { data, form }: { data: PageData; form: ActionData } = $props();
  let kind = $state('expense');
  let walletGroupId = $state('');
  let accountId = $state('');
  let destinationGroupId = $state('');
  let destinationAccountId = $state('');
  let dateToday = new Date().toISOString().slice(0, 10);
  const sourceAccounts = $derived(data.accounts.filter((account) => !account.archived_at && account.wallet_group_id === walletGroupId));
  const destinationAccounts = $derived(data.accounts.filter((account) => !account.archived_at && account.wallet_group_id === destinationGroupId && account.id !== accountId));
  const accountLabel = (id: string) => {
    const account = data.accounts.find((row) => row.id === id);
    const group = data.groups.find((row) => row.id === account?.wallet_group_id);
    return `${group?.name ?? 'Wallet'}  | ${account?.currency ?? ''}${account?.channel ? `  | ${account.channel}` : ''}`;
  };
  const categoryLabel = (id: string | null) => data.categories.find((row) => row.id === id)?.name ?? 'Uncategorised';
  const historyPageHref = (page: number) => { const params = new URLSearchParams({ page: String(page) }); if (data.walletFilter) params.set('wallet', data.walletFilter); return `?${params.toString()}#transaction-history`; };
</script>
<svelte:head><title>Transactions — Budget</title></svelte:head>
<div class="app-frame">
  <aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link active" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link" href="/investments"><WalletCards size={18}/> Investments</a><a class="side-link" href="/budgets"><WalletCards size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
  <main class="main-area"><header class="topbar"><div><p class="date-label">Your money, clearly</p><p class="topbar-title">Transactions</p></div><a class="add-button" href="#new-transaction"><Plus size={18}/> Add transaction</a></header>
    <div class="content-wrap"><section class="welcome-row"><div><p class="eyebrow">Ledger</p><h1>Every move, <span class="accent-period">accounted for.</span></h1><p class="welcome-copy">Record income, spending, and transfers between your wallets.</p></div></section>
      {#if data.loadError}<div class="setup-banner"><div><strong>Database setup needed</strong><p>{data.loadError}. Run the setup SQL in Supabase, then refresh.</p></div></div>{/if}
      {#if form?.message}<p class="form-alert" role="alert">{form.message}</p>{/if}
      <section class="section-block transaction-entry-section"><div class="section-heading"><div><p class="eyebrow">New entry</p><h2>Record a transaction</h2><p class="section-caption">Add a movement to the right wallet in a few steps.</p></div></div>
        <form id="new-transaction" method="POST" action="?/create" class="feature-form" use:enhance={handleInvestmentSubmit}>
          <label>Type<select name="kind" bind:value={kind}><option value="expense">Spending</option><option value="income">Income</option><option value="transfer">Transfer</option></select></label>
          <label>From wallet<select value={walletGroupId} onchange={(event) => { walletGroupId = event.currentTarget.value; accountId = ''; }} required><option value="" disabled>Choose a wallet</option>{#each data.groups as group}<option value={group.id}>{group.name}</option>{/each}</select></label>
          <label>From account<select name="account_id" bind:value={accountId} required disabled={!walletGroupId}><option value="" disabled>Choose a currency or sub-wallet</option>{#each sourceAccounts as account}<option value={account.id}>{account.currency === 'USD' ? 'USD' : 'ZiG'}{account.channel ? `  | ${account.channel === 'ecocash' ? 'EcoCash' : account.channel === 'bank' ? 'Bank' : 'Cash'}` : ''}</option>{/each}</select></label>
          {#if kind === 'transfer'}<label>To wallet<select value={destinationGroupId} onchange={(event) => { destinationGroupId = event.currentTarget.value; destinationAccountId = ''; }} required><option value="" disabled>Choose destination wallet</option>{#each data.groups as group}<option value={group.id}>{group.name}</option>{/each}</select></label><label>To account<select name="destination_account_id" bind:value={destinationAccountId} required disabled={!destinationGroupId}><option value="" disabled>Choose a currency or sub-wallet</option>{#each destinationAccounts as account}<option value={account.id}>{account.currency === 'USD' ? 'USD' : 'ZiG'}{account.channel ? `  | ${account.channel === 'ecocash' ? 'EcoCash' : account.channel === 'bank' ? 'Bank' : 'Cash'}` : ''}</option>{/each}</select></label>{/if}
          <label>Amount<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="0.00" required/></label>
          {#if kind === 'transfer'}<label>Amount received (for another currency)<input name="destination_amount" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="Only for cross-currency transfers"/></label><label>Exchange rate<input name="exchange_rate" type="number" min="0.0000000001" step="any" inputmode="decimal" placeholder="Only for cross-currency transfers"/></label><label>Transfer fee<input name="fee_amount" type="number" min="0" step="0.01" inputmode="decimal" value="0"/></label>{/if}
          <label>Category<select name="category_id" required={kind !== 'transfer'}><option value="">{kind === 'transfer' ? 'No fee category' : 'Choose a category'}</option>{#each data.categories.filter((category) => kind === 'income' ? category.kind === 'income' : category.kind === 'expense') as category}<option value={category.id}>{category.name}{kind === 'transfer' ? '  | fee' : ''}</option>{/each}</select></label>
          <label>Date<input name="occurred_on" type="date" value={dateToday} required/></label>
          <label class="form-wide">Note<input name="description" maxlength="240" placeholder="What was this for?"/></label>
          <div class="form-wide form-footer"><p>Amounts stay in the selected wallet’s currency.</p><button class="primary-button" type="submit"><Plus size={17}/> Save transaction</button></div>
        </form>
      </section>
      {#if data.investmentMovements.length}<section class="section-block investment-ledger-section"><div class="section-heading"><div><p class="eyebrow">Linked wallet transfers</p><h2>Investment funding</h2><p class="section-caption">These move money between your personal wallets and investment accounts; they are not income or spending.</p></div></div><div class="ledger-table-wrap"><table class="ledger-table"><thead><tr><th>Movement</th><th>Wallet</th><th>Investment account</th><th>Date</th><th class="amount-cell">Amount</th></tr></thead><tbody>{#each data.investmentMovements as movement}<tr><td><div class="ledger-title"><span class="transaction-icon transfer-icon">{#if movement.kind === 'deposit'}<ArrowUpRight size={16}/>{:else}<ArrowDownLeft size={16}/>{/if}</span><div><strong>{movement.kind === 'deposit' ? 'Deposit to investment' : 'Withdrawal from investment'}</strong><small>{movement.description || 'Investment transfer'}</small></div></div></td><td>{accountLabel(movement.wallet_account_id)}</td><td>{movement.investment_account?.[0]?.name ?? 'Investment account'}</td><td>{new Date(movement.occurred_at).toLocaleDateString()}</td><td class="amount-cell"><strong class:income-value={movement.kind === 'withdrawal'} class:expense-value={movement.kind === 'deposit'}>{movement.kind === 'withdrawal' ? '+' : '−'}{movement.amount}</strong></td></tr>{/each}</tbody></table></div></section>{/if}
      <section class="section-block" id="transaction-history"><div class="section-heading"><div><p class="eyebrow">Your ledger</p><h2>Transaction history</h2></div><span class="section-caption">{data.totalTransactions} {data.totalTransactions === 1 ? 'entry' : 'entries'}{data.walletFilterName ? `  |  ${data.walletFilterName}` : ''}</span></div>
        <form method="GET" action="/transactions#transaction-history" class="history-filter"><label for="history-wallet">Show activity for</label><select id="history-wallet" name="wallet" value={data.walletFilter}><option value="">All wallets</option>{#each data.groups as group}<option value={group.id}>{group.name}{group.kind === 'personal' ? '  |  Personal' : '  |  Project'}</option>{/each}</select><button class="overview-shortcut" type="submit">Filter history</button>{#if data.walletFilter}<a href="/transactions#transaction-history">Clear</a>{/if}</form>
        {#if data.transactions.length}<div class="ledger-table-wrap"><table class="ledger-table"><thead><tr><th>Transaction</th><th>Wallet</th><th>Category / destination</th><th>Date</th><th class="amount-cell">Amount</th></tr></thead><tbody>{#each data.transactions as transaction}<tr><td><div class="ledger-title"><span class="transaction-icon" class:transfer-icon={transaction.kind === 'transfer'}>{#if transaction.kind === 'income'}<ArrowDownLeft size={16}/>{:else if transaction.kind === 'expense'}<ArrowUpRight size={16}/>{:else}<ArrowLeftRight size={16}/>{/if}</span><div><strong>{transaction.description || (transaction.kind === 'income' ? 'Income' : transaction.kind === 'expense' ? 'Spending' : 'Transfer')}</strong><small>{transaction.kind === 'income' ? 'Income' : transaction.kind === 'expense' ? 'Spending' : 'Transfer'}</small></div></div></td><td>{accountLabel(transaction.account_id)}</td><td>{transaction.kind === 'transfer' ? `→ ${accountLabel(transaction.destination_account_id)}` : categoryLabel(transaction.category_id)}{#if transaction.kind === 'transfer' && Number(transaction.fee_amount) > 0}<small class="ledger-subline">Fee: {transaction.fee_amount}</small>{/if}</td><td>{new Date(transaction.occurred_at).toLocaleDateString()}</td><td class="amount-cell"><strong class:income-value={transaction.kind === 'income'} class:expense-value={transaction.kind === 'expense'}>{transaction.kind === 'income' ? '+' : transaction.kind === 'expense' ? '−' : ''}{transaction.amount}</strong></td></tr>{/each}</tbody></table></div>
          {#if data.totalPages > 1}<nav class="pagination" aria-label="Transaction pages"><span>Showing {(data.page - 1) * data.pageSize + 1}–{Math.min(data.page * data.pageSize, data.totalTransactions)} of {data.totalTransactions}</span><div><a class:disabled-page={data.page <= 1} aria-disabled={data.page <= 1} href={data.page <= 1 ? '#transaction-history' : historyPageHref(data.page - 1)}>Previous</a><span class="page-count">Page {data.page} of {data.totalPages}</span><a class:disabled-page={data.page >= data.totalPages} aria-disabled={data.page >= data.totalPages} href={data.page >= data.totalPages ? '#transaction-history' : historyPageHref(data.page + 1)}>Next</a></div></nav>{/if}
        {:else}<div class="empty-card"><div class="empty-icon"><ArrowLeftRight size={23}/></div><h3>{data.walletFilterName ? `No transactions for ${data.walletFilterName} yet` : 'No transactions yet'}</h3><p>{data.walletFilterName ? 'Try another wallet or clear the filter to see all activity.' : 'Your income, spending, and transfers will appear here.'}</p></div>{/if}
      </section>
    </div>
  </main>
  <nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a class="mobile-nav-active" href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a href="/investments"><WalletCards size={18}/><span>Investments</span></a><a href="/budgets"><WalletCards size={18}/><span>Budgets</span></a><a href="/insights"><BarChart3 size={18}/><span>Insights</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav>
</div>
