<script lang="ts">
  import { ArrowLeftRight, BarChart3, LayoutDashboard, LogOut, Plus, Settings2, WalletCards, ArchiveRestore, FolderKanban, Tags } from 'lucide-svelte';
  import type { PageData, ActionData } from './$types';
  let { data, form }: { data: PageData; form: ActionData } = $props();
  const channelLabels: Record<string, string> = { ecocash: 'EcoCash', bank: 'Bank', cash: 'Cash' };
</script>
<svelte:head><title>Settings — Budget</title></svelte:head>
<div class="app-frame">
  <aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link" href="/budgets"><WalletCards size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link active" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
  <main class="main-area"><header class="topbar"><div><p class="date-label">Your setup</p><p class="topbar-title">Settings</p></div></header>
    <div class="content-wrap"><section class="welcome-row"><div><p class="eyebrow">Make it yours</p><h1>Set up your <span class="accent-period">money space.</span></h1><p class="welcome-copy">Create project wallets and the categories you use to organise activity.</p></div></section>
      {#if data.loadError}<div class="setup-banner"><div><strong>Database setup needed</strong><p>{data.loadError}. Run the setup SQL in Supabase, then refresh.</p></div></div>{/if}{#if form?.message}<p class="form-alert" role="alert">{form.message}</p>{/if}
      <section class="settings-grid">
        <article class="feature-card"><div class="feature-title"><span class="wallet-icon"><FolderKanban size={18}/></span><div><p class="eyebrow">Project accounts</p><h2>Project wallets</h2></div></div><p class="feature-copy">Name each project and choose whether it tracks USD, ZiG, or both.</p>
          <form method="POST" action="?/createProject" class="settings-form"><label class="settings-field">Wallet name<input name="name" maxlength="80" placeholder="e.g. Garden project" required/></label><fieldset class="currency-choice"><legend>Track currencies</legend><label><input type="checkbox" name="currencies" value="USD" checked/> USD</label><label><input type="checkbox" name="currencies" value="ZIG" checked/> ZiG</label></fieldset><button class="primary-button compact-button" type="submit"><Plus size={16}/> Create wallet</button></form>
          <div class="settings-list wallet-settings-list">{#each data.groups.filter((group) => group.kind === 'project') as group}<div class="project-setting-row"><div class="project-setting-summary"><div><strong>{group.name}</strong><span>{group.archived_at ? 'Archived' : 'Active'} · {group.currencies.length ? group.currencies.map((currency: string) => currency === 'USD' ? 'USD' : 'ZiG').join(' + ') : 'No active currencies'}</span></div><div class="project-row-actions"><details class="wallet-edit"><summary>Edit</summary><form method="POST" action="?/updateProject" class="wallet-edit-form"><input type="hidden" name="id" value={group.id}/><label class="settings-field">Wallet name<input name="name" maxlength="80" value={group.name} required/></label><fieldset class="currency-choice"><legend>Active currencies</legend><label><input type="checkbox" name="currencies" value="USD" checked={group.currencies.includes('USD')}/> USD</label><label><input type="checkbox" name="currencies" value="ZIG" checked={group.currencies.includes('ZIG')}/> ZiG</label></fieldset><button class="primary-button compact-button" type="submit">Save changes</button><p class="form-hint">Removed currencies are archived with their transaction history preserved.</p></form></details><form method="POST" action="?/setProjectArchive"><input type="hidden" name="id" value={group.id}/><input type="hidden" name="archived" value={group.archived_at ? 'false' : 'true'}/><button class="text-button" type="submit">{#if group.archived_at}<ArchiveRestore size={16}/> Restore{:else}<ArchiveRestore size={16}/> Archive{/if}</button></form></div></div></div>{/each}{#if !data.groups.some((group) => group.kind === 'project')}<p class="list-empty">Your project wallets will show here.</p>{/if}</div>
        </article>
        <article class="feature-card"><div class="feature-title"><span class="wallet-icon"><Tags size={18}/></span><div><p class="eyebrow">Transaction labels</p><h2>Categories</h2></div></div><p class="feature-copy">Keep income and spending categories separate for clearer budgets and reports.</p>
          <form method="POST" action="?/createCategory" class="settings-form category-form"><label class="settings-field">Category name<input id="category-name" name="name" maxlength="60" placeholder="e.g. Transport" required/></label><label class="settings-field">Category type<select name="kind"><option value="expense">Spending</option><option value="income">Income</option></select></label><button class="primary-button compact-button" type="submit"><Plus size={16}/> Add category</button></form>
          <div class="settings-list">{#each data.categories as category}<div class="settings-row"><div><strong>{category.name}</strong><span>{category.kind === 'income' ? 'Income' : 'Spending'}</span></div><span class="category-chip">{category.kind === 'income' ? 'IN' : 'OUT'}</span></div>{/each}{#if !data.categories.length}<p class="list-empty">Add categories for your transactions.</p>{/if}</div>
        </article>
      </section>
      <section class="section-block"><div class="section-heading"><div><p class="eyebrow">Starting point</p><h2>Opening balances</h2></div><span class="section-caption">Set what is already in each wallet</span></div><div class="opening-list">{#each data.accounts as account}<form method="POST" action="?/setOpeningBalance" class="opening-row"><input type="hidden" name="id" value={account.id}/><div><strong>{account.group_name} · {account.currency === 'USD' ? 'USD' : 'ZiG'}</strong><span>{account.group_kind === 'personal' ? (channelLabels[account.channel ?? ''] ?? 'Personal') : 'Project balance'}</span></div><label><span class="sr-only">Opening balance</span><input name="opening_balance" type="number" min="0" step="0.01" inputmode="decimal" value={account.opening_balance} required/></label><button class="primary-button compact-button" type="submit">Save</button></form>{/each}</div></section>
      <section class="personal-note"><span class="wallet-icon"><WalletCards size={18}/></span><div><strong>Personal wallet</strong><p>Personal is created automatically with EcoCash, Bank, and Cash sub-wallets in USD and ZiG. Those balances roll up to your Personal wallet.</p></div></section>
    </div>
  </main>
  <nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a href="/budgets"><WalletCards size={18}/><span>Budgets</span></a><a href="/insights"><BarChart3 size={18}/><span>Insights</span></a><a class="mobile-nav-active" href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav>
</div>
