<script lang="ts">
  import { ArrowLeftRight, BarChart3, BriefcaseBusiness, CircleDollarSign, LayoutDashboard, LogOut, Settings2, Target, TrendingUp, WalletCards } from 'lucide-svelte';
  import InvestmentNav from '$lib/components/InvestmentNav.svelte';
  import type { PageData } from './$types';
  let { data }: { data: PageData } = $props();
  const money = (value: number | string, currency: string) => `${currency === 'USD' ? '$' : 'ZiG '}${Number(value ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const dateLabel = (value: string | null) => value ? new Date(`${value}T12:00:00`).toLocaleDateString() : 'No data yet';
  const shareOf = (value: number, total: number) => total > 0 ? `${(value / total * 100).toFixed(1)}%` : '0.0%';
  function chartModel(rows: any[], keys: string[], currency: string, mode: 'money' | 'index' = 'money') {
    const left = 78; const right = 660; const top = 18; const bottom = 205;
    const values = rows.flatMap((row) => keys.map((key) => Number(row[key] ?? 0))).filter(Number.isFinite);
    let low = Math.min(...values); let high = Math.max(...values);
    if (!Number.isFinite(low)) { low = 0; high = 1; }
    const span = high - low || Math.max(Math.abs(high) * 0.1, 1);
    low -= span * 0.08; high += span * 0.08;
    const dateTimes = rows.map((row) => Date.parse(`${row.date}T12:00:00Z`));
    const firstTime = dateTimes[0] ?? 0; const lastTime = dateTimes.at(-1) ?? firstTime;
    const xFor = (index: number) => lastTime > firstTime
      ? left + (dateTimes[index] - firstTime) / (lastTime - firstTime) * (right - left)
      : left + index * (right - left) / Math.max(rows.length - 1, 1);
    const yFor = (value: number) => bottom - (value - low) / (high - low) * (bottom - top);
    const formatter = new Intl.NumberFormat('en-US', { maximumFractionDigits: high - low < 10 ? 2 : 0 });
    const yTicks = Array.from({ length: 5 }, (_, index) => {
      const value = high - index * (high - low) / 4;
      const label = mode === 'index' ? `${value.toFixed(2)}×` : currency === 'USD' ? `$${formatter.format(value)}` : `ZiG ${formatter.format(value)}`;
      return { y: yFor(value), label };
    });
    const indices = [...new Set([0, Math.floor((rows.length - 1) / 2), rows.length - 1])];
    const xTicks = indices.map((index) => ({ x: xFor(index), label: rows[index]?.date ? new Date(`${rows[index].date}T12:00:00`).toLocaleDateString('en', { month: 'short', year: '2-digit' }) : '' }));
    const paths = Object.fromEntries(keys.map((key) => [key, rows.map((row, index) => `${xFor(index).toFixed(1)},${yFor(Number(row[key] ?? 0)).toFixed(1)}`).join(' ')]));
    return { left, right, top, bottom, yTicks, xTicks, paths };
  }
  const changeClass = (value: number | null) => value === null ? '' : value >= 0 ? 'gain' : 'loss';
</script>

<svelte:head><title>Investment Analysis — Budget</title><meta name="description" content="Detailed performance, allocation, stock history and forex risk analysis." /></svelte:head>
<div class="app-frame">
  <aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link active" href="/investments"><TrendingUp size={18}/> Investments</a><a class="side-link" href="/budgets"><Target size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
  <main class="main-area">
    <header class="topbar"><div><p class="date-label">Portfolio performance and risk</p><p class="topbar-title">Investment Analysis</p></div></header>
    <InvestmentNav active="analysis" />
    <div class="content-wrap investment-content analysis-content">
      <section class="welcome-row"><div><p class="eyebrow">Portfolio intelligence</p><h1>Investment analysis<span class="accent-period">.</span></h1><p class="welcome-copy">Track market value and invested capital separately. USD and ZiG stay on their own scales; values use the prices and daily equity you record.</p></div></section>
      {#if data.loadError}<div class="setup-banner"><div><strong>Some investment data could not be loaded</strong><p>{data.loadError}. Check that all investment migrations have been applied.</p></div></div>{/if}

      <section class="analysis-summary-grid" aria-label="Portfolio summary by currency">
        {#each data.summaries as summary}
          <article class="analysis-panel summary-panel"><div class="analysis-panel-heading"><div><p class="eyebrow">Portfolio summary</p><h2>{summary.currency === 'USD' ? 'US dollars' : 'Zimbabwe Gold'}</h2></div><span class="currency-badge" class:zig-badge={summary.currency === 'ZIG'}>{summary.currency === 'USD' ? 'USD' : 'ZiG'}</span></div>
            <strong class="analysis-total">{money(summary.value, summary.currency)}</strong><span class="analysis-muted">Current estimated portfolio value</span>
            <div class="analysis-stat-grid"><div><span>Net contributions</span><strong>{money(summary.netContribution, summary.currency)}</strong></div><div><span>Realized stock gains</span><strong class={changeClass(summary.realized)}>{money(summary.realized, summary.currency)}</strong></div><div><span>Unrealized stock gains</span><strong class={changeClass(summary.unrealized)}>{money(summary.unrealized, summary.currency)}</strong></div><div><span>Forex account gain</span><strong class={changeClass(summary.forexGain)}>{money(summary.forexGain, summary.currency)}</strong></div><div><span>Total return</span><strong class={changeClass(summary.returnPercent)}>{summary.returnPercent === null ? '—' : `${summary.returnPercent.toFixed(2)}%`}</strong></div></div>
            {#if summary.accounts.some((account: any) => account.pending)}<p class="analysis-note">Some holdings have no recorded closing price. They are carried at cost while price performance is pending.</p>{/if}
          </article>
        {/each}
      </section>

      <section class="analysis-section"><div class="section-heading"><div><p class="eyebrow">Performance history</p><h2>Portfolio value and contributions</h2><p class="section-caption">Deposits and opening positions increase contributed capital; investment gains appear as the gap between the two lines.</p></div></div>
        <div class="analysis-chart-grid">{#each data.growth as series}<article class="analysis-panel analysis-chart-card"><div class="analysis-panel-heading"><h3>{series.currency === 'USD' ? 'US dollar portfolio' : 'ZiG portfolio'}</h3><span class="currency-badge" class:zig-badge={series.currency === 'ZIG'}>{series.currency === 'USD' ? 'USD' : 'ZiG'}</span></div>
          {#if series.points.length > 1}{@const plot = chartModel(series.points, ['value', 'contribution'], series.currency)}<svg class="analysis-line-chart" viewBox="0 0 680 258" role="img" aria-label={`${series.currency} portfolio value compared with net contributions over time`}><text class="chart-axis-title" transform="translate(15 112) rotate(-90)">Value ({series.currency})</text>{#each plot.yTicks as tick}<line x1={plot.left} y1={tick.y} x2={plot.right} y2={tick.y} class="chart-gridline"/><text x={plot.left - 9} y={tick.y + 3} text-anchor="end" class="chart-tick-label">{tick.label}</text>{/each}<line x1={plot.left} y1={plot.top} x2={plot.left} y2={plot.bottom} class="chart-axis"/><line x1={plot.left} y1={plot.bottom} x2={plot.right} y2={plot.bottom} class="chart-axis"/><polyline points={plot.paths.value} class="chart-value-line"/><polyline points={plot.paths.contribution} class="chart-contribution-line"/>{#each plot.xTicks as tick}<line x1={tick.x} y1={plot.bottom} x2={tick.x} y2={plot.bottom + 4} class="chart-axis"/><text x={tick.x} y="224" text-anchor="middle" class="chart-tick-label">{tick.label}</text>{/each}<text x={(plot.left + plot.right) / 2} y="249" text-anchor="middle" class="chart-axis-title">Date</text></svg><div class="analysis-chart-legend"><span><i class="legend-value"></i>Portfolio value</span><span><i class="legend-contribution"></i>Net contributions</span><span class="chart-range-label">{dateLabel(series.points[0]!.date)} – {dateLabel(series.points[series.points.length - 1]!.date)}</span></div><div class="analysis-chart-foot"><span>Latest value <strong>{money(series.points[series.points.length - 1]!.value, series.currency)}</strong></span><span>Contributions <strong>{money(series.points[series.points.length - 1]!.contribution, series.currency)}</strong></span></div>
          {:else}<div class="analysis-empty-chart">Record a purchase, transfer, closing price, or forex valuation to build a portfolio history.</div>{/if}</article>{/each}</div>
      </section>

      <section class="analysis-section"><div class="section-heading"><div><p class="eyebrow">Portfolio mix</p><h2>Allocation</h2><p class="section-caption">Values are shown separately by currency. Stock counters are valued at their latest close or carried at cost.</p></div></div>
        <div class="allocation-grid">{#each data.summaries as summary}<article class="analysis-panel allocation-panel"><div class="analysis-panel-heading"><h3>{summary.currency === 'USD' ? 'US dollars' : 'Zimbabwe Gold'}</h3><span class="currency-badge" class:zig-badge={summary.currency === 'ZIG'}>{summary.currency === 'USD' ? 'USD' : 'ZiG'}</span></div>
          <p class="allocation-scale-note">Bar length and percentage show share of this currency’s current portfolio value.</p>
          <h4>By investment type</h4>{#each ['stocks', 'forex'] as kind}{@const bucketValue = summary.accounts.filter((account: any) => account.kind === kind).reduce((sum: number, account: any) => sum + account.value, 0)}<div class="allocation-row"><div><span>{kind === 'stocks' ? 'Stocks' : 'Forex'}</span><strong>{money(bucketValue, summary.currency)} <small>{shareOf(bucketValue, summary.value)}</small></strong></div><div class="allocation-track"><span style={`width:${summary.value ? Math.max(0, Math.min(100, bucketValue / summary.value * 100)) : 0}%`}></span></div></div>{/each}
          <h4>By account</h4>{#each summary.accounts as account}<div class="allocation-row"><div><span>{account.name}</span><strong>{money(account.value, summary.currency)} <small>{shareOf(account.value, summary.value)}</small></strong></div><div class="allocation-track"><span style={`width:${summary.value ? Math.max(0, Math.min(100, account.value / summary.value * 100)) : 0}%`}></span></div></div>{:else}<p class="analysis-muted">No accounts in this currency yet.</p>{/each}
          <h4>By counter</h4>{#each summary.accounts.filter((account: any) => account.kind === 'stocks').flatMap((account: any) => account.positions.filter((position: any) => position.shares > 0).map((position: any) => ({ ...position, value: position.marketValue }))) as position}<div class="allocation-row"><div><span>{position.ticker} · {position.company_name}</span><strong>{money(position.value, summary.currency)} <small>{shareOf(position.value, summary.value)}</small></strong></div><div class="allocation-track"><span style={`width:${summary.value ? Math.max(0, Math.min(100, position.value / summary.value * 100)) : 0}%`}></span></div></div>{:else}<p class="analysis-muted">No active stock holdings yet.</p>{/each}
        </article>{/each}</div>
      </section>

      <section class="analysis-section"><div class="section-heading"><div><p class="eyebrow">Holdings and accounts</p><h2>Performance table</h2><p class="section-caption">Stock returns include realized gains and current unrealized gains; forex uses net contributions and the latest flow-adjusted equity.</p></div></div>
        <div class="analysis-panel table-panel"><div class="analysis-table-wrap"><table class="analysis-table"><thead><tr><th>Investment</th><th>Type</th><th>Currency</th><th>Current value</th><th>Cost / contributions</th><th>Gain / loss</th><th>Return</th><th>Latest price / valuation</th></tr></thead><tbody>
          {#each data.performance as row}<tr><td><strong>{row.name}</strong>{#if row.accountName}<small>{row.accountName}</small>{/if}</td><td>{row.kind}</td><td>{row.currency === 'USD' ? 'USD' : 'ZiG'}</td><td>{money(row.value, row.currency)}</td><td>{money(row.cost, row.currency)}</td><td class={changeClass(row.pending ? null : row.gain)}>{row.pending ? 'Pending price' : money(row.gain, row.currency)}</td><td class={changeClass(row.pending ? null : row.returnPercent)}>{row.pending || row.returnPercent === null ? '—' : `${row.returnPercent.toFixed(2)}%`}</td><td>{dateLabel(row.latestDate)}</td></tr>
          {:else}<tr><td colspan="8" class="analysis-table-empty">Add an investment account and enter holdings to see performance here.</td></tr>{/each}
        </tbody></table></div></div>
      </section>

      <section class="analysis-section"><div class="section-heading"><div><p class="eyebrow">Counter level</p><h2>Stock detail</h2><p class="section-caption">Expand a counter to review open quantity, cost, current close, individual trades, and recorded price history.</p></div></div>
        <div class="stock-detail-list">{#each data.summaries.flatMap((summary: any) => summary.accounts.filter((account: any) => account.kind === 'stocks').flatMap((account: any) => account.positions.map((position: any) => ({ ...position, currency: account.currency, accountName: account.name })))) as position}
          <details class="analysis-panel stock-detail"><summary><span><strong>{position.ticker} · {position.company_name}</strong><small>{position.accountName} · {position.shares.toLocaleString()} shares · cost {money(position.costBasis, position.currency)}</small></span><span class="stock-detail-value"><strong>{money(position.marketValue, position.currency)}</strong><small>{position.closingPrice === null ? 'Awaiting close' : `Latest close ${money(position.closingPrice, position.currency)} · ${dateLabel(position.quoteDate)}`}</small></span></summary>
            <div class="stock-detail-body"><div class="analysis-stat-grid"><div><span>Shares held</span><strong>{position.shares.toLocaleString()}</strong></div><div><span>Average purchase cost</span><strong>{money(position.shares ? position.costBasis / position.shares : 0, position.currency)} / share</strong></div><div><span>Realized gains</span><strong class={changeClass(position.realized)}>{money(position.realized, position.currency)}</strong></div><div><span>Unrealized gains</span><strong class={changeClass(position.unrealized)}>{position.unrealized === null ? 'Awaiting close' : money(position.unrealized, position.currency)}</strong></div></div>
              {#if position.history.length > 1}{@const plot = chartModel(position.history, ['value'], position.currency)}<div class="detail-chart-wrap"><h4>Recorded closing price history</h4><svg class="analysis-line-chart detail-line-chart" viewBox="0 0 680 258" role="img" aria-label={`${position.ticker} closing price over time`}><text class="chart-axis-title" transform="translate(15 112) rotate(-90)">Price ({position.currency})</text>{#each plot.yTicks as tick}<line x1={plot.left} y1={tick.y} x2={plot.right} y2={tick.y} class="chart-gridline"/><text x={plot.left - 9} y={tick.y + 3} text-anchor="end" class="chart-tick-label">{tick.label}</text>{/each}<line x1={plot.left} y1={plot.top} x2={plot.left} y2={plot.bottom} class="chart-axis"/><line x1={plot.left} y1={plot.bottom} x2={plot.right} y2={plot.bottom} class="chart-axis"/><polyline points={plot.paths.value} class="chart-value-line"/>{#each plot.xTicks as tick}<line x1={tick.x} y1={plot.bottom} x2={tick.x} y2={plot.bottom + 4} class="chart-axis"/><text x={tick.x} y="224" text-anchor="middle" class="chart-tick-label">{tick.label}</text>{/each}<text x={(plot.left + plot.right) / 2} y="249" text-anchor="middle" class="chart-axis-title">Date</text></svg><div class="analysis-chart-legend"><span><i class="legend-value"></i>Closing price per share</span></div><div class="analysis-chart-foot"><span>{dateLabel(position.history[0].date)} · {money(position.history[0].value, position.currency)}</span><span>{dateLabel(position.history.at(-1).date)} · {money(position.history.at(-1).value, position.currency)}</span></div></div>{:else}<p class="analysis-muted">Record another closing price to show a price history chart.</p>{/if}
              <h4>Purchase lots and sales</h4><div class="analysis-table-wrap"><table class="analysis-table compact-analysis-table"><thead><tr><th>Date</th><th>Activity</th><th>Shares</th><th>Price / share</th><th>Charges</th><th>Realized gain</th></tr></thead><tbody>{#each position.trades as trade}<tr><td>{dateLabel(trade.occurred_at?.slice(0, 10))}</td><td>{trade.kind === 'opening' ? 'Imported lot' : trade.kind === 'buy' ? 'Purchase' : 'Sale'}</td><td>{Number(trade.quantity).toLocaleString()}</td><td>{money(trade.unit_price, position.currency)}</td><td>{money(trade.fees, position.currency)}</td><td class={changeClass(trade.realized_profit === null ? null : Number(trade.realized_profit))}>{trade.realized_profit === null ? '—' : money(trade.realized_profit, position.currency)}</td></tr>{:else}<tr><td colspan="6" class="analysis-table-empty">No trade lots recorded.</td></tr>{/each}</tbody></table></div>
            </div>
          </details>{:else}<div class="analysis-panel analysis-empty-chart">No stock counters recorded. Add a stock holding to see its cost lots and price history.</div>{/each}
        </div>
      </section>

      <section class="analysis-section"><div class="section-heading"><div><p class="eyebrow">Trading account health</p><h2>Forex performance</h2><p class="section-caption">Daily changes subtract deposits and withdrawals between snapshots before calculating return. Risk figures use the compounded flow-adjusted return series.</p></div></div>
        <div class="forex-analysis-grid">{#each data.forexRisk as risk}<article class="analysis-panel forex-risk-card"><div class="analysis-panel-heading"><div><p class="eyebrow">Forex account</p><h3>{risk.name}</h3></div><span class="currency-badge" class:zig-badge={risk.currency === 'ZIG'}>{risk.currency === 'USD' ? 'USD' : 'ZiG'}</span></div>
            <div class="forex-risk-metrics"><div><span>Best day</span><strong class="gain">{risk.best ? `${risk.best.returnPercent.toFixed(2)}%` : '—'}</strong><small>{risk.best ? dateLabel(risk.best.date) : 'Need 2 valuations'}</small></div><div><span>Worst day</span><strong class="loss">{risk.worst ? `${risk.worst.returnPercent.toFixed(2)}%` : '—'}</strong><small>{risk.worst ? dateLabel(risk.worst.date) : 'Need 2 valuations'}</small></div><div><span>Maximum drawdown</span><strong class="loss">{risk.points.length > 1 ? `${risk.maxDrawdown.toFixed(2)}%` : '—'}</strong><small>Peak to trough</small></div></div>
            {#if risk.points.length > 1}{@const plot = chartModel(risk.points, ['nav'], risk.currency, 'index')}<svg class="analysis-line-chart forex-nav-chart" viewBox="0 0 680 258" role="img" aria-label={`${risk.name} flow-adjusted growth index over time`}><text class="chart-axis-title" transform="translate(15 112) rotate(-90)">Growth index (start = 1.00)</text>{#each plot.yTicks as tick}<line x1={plot.left} y1={tick.y} x2={plot.right} y2={tick.y} class="chart-gridline"/><text x={plot.left - 9} y={tick.y + 3} text-anchor="end" class="chart-tick-label">{tick.label}</text>{/each}<line x1={plot.left} y1={plot.top} x2={plot.left} y2={plot.bottom} class="chart-axis"/><line x1={plot.left} y1={plot.bottom} x2={plot.right} y2={plot.bottom} class="chart-axis"/><polyline points={plot.paths.nav} class="chart-value-line"/>{#each plot.xTicks as tick}<line x1={tick.x} y1={plot.bottom} x2={tick.x} y2={plot.bottom + 4} class="chart-axis"/><text x={tick.x} y="224" text-anchor="middle" class="chart-tick-label">{tick.label}</text>{/each}<text x={(plot.left + plot.right) / 2} y="249" text-anchor="middle" class="chart-axis-title">Date</text></svg><div class="analysis-chart-legend"><span><i class="legend-value"></i>Flow-adjusted growth index</span><span>Index starts at 1.00 on the first valuation.</span></div>{/if}
            <h4>Daily flow-adjusted changes</h4><div class="analysis-table-wrap"><table class="analysis-table compact-analysis-table"><thead><tr><th>Date</th><th>Closing equity</th><th>Net-of-flow change</th><th>Daily return</th></tr></thead><tbody>{#each [...risk.points].reverse().slice(0, 20) as point}<tr><td>{dateLabel(point.date)}</td><td>{money(point.value, risk.currency)}</td><td class={changeClass(point.change)}>{point.change === 0 ? money(0, risk.currency) : money(point.change, risk.currency)}</td><td class={changeClass(point.returnPercent)}>{point.returnPercent === null ? '—' : `${point.returnPercent.toFixed(2)}%`}</td></tr>{:else}<tr><td colspan="4" class="analysis-table-empty">Record daily closing equity to build forex performance.</td></tr>{/each}</tbody></table></div>
          </article>{:else}<div class="analysis-panel analysis-empty-chart">No forex accounts yet. Add a forex account and record daily closing equity to calculate flow-adjusted performance and drawdown.</div>{/each}</div>
      </section>
      <footer class="dashboard-footer"><span>Investment data is based on your recorded trades, prices, transfers, and valuations.</span><span>USD and ZiG are not converted or combined.</span></footer>
    </div>
  </main>
  <nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a class="mobile-nav-active" href="/investments"><TrendingUp size={18}/><span>Investments</span></a><a href="/budgets"><Target size={18}/><span>Budgets</span></a><a href="/insights"><BarChart3 size={18}/><span>Insights</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav>
</div>
