<script lang="ts">
  import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, BarChart3, LayoutDashboard, LogOut, Settings2, Target, TrendingUp, WalletCards } from 'lucide-svelte';
  import InvestmentNav from '$lib/components/InvestmentNav.svelte';
  import { enhance } from '$app/forms';
  import { handleInvestmentSubmit } from '$lib/investments/feedback';
  import type { ActionData, PageData } from './$types';
  let { data, form }: { data: PageData; form: ActionData } = $props();
  const money = (value: number | string, currency: string) => `${currency === 'USD' ? '$' : 'ZiG '}${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const accountName = (id: string) => data.accounts.find((account: any) => account.id === id)?.name ?? 'Investment account';
  const accountCurrency = (id: string) => data.accounts.find((account: any) => account.id === id)?.currency ?? 'USD';
</script>
<svelte:head><title>Investment transfers — Budget</title></svelte:head>
<div class="app-frame"><aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link active" href="/investments"><TrendingUp size={18}/> Investments</a><a class="side-link" href="/budgets"><Target size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
<main class="main-area"><header class="topbar"><div><p class="date-label">Move money to or from investments</p><p class="topbar-title">Transfers</p></div></header><InvestmentNav active="transfers"/><div class="content-wrap investment-content">
  <section class="welcome-row"><div><p class="eyebrow">Capital movements</p><h1>Transfers<span class="accent-period">.</span></h1><p class="welcome-copy">Fund a brokerage account from a personal wallet, or withdraw proceeds back to one.</p></div></section>
  {#if data.loadError}<div class="setup-banner"><div><strong>Investment data is not ready</strong><p>{data.loadError}. Apply the investments migration in Supabase, then refresh.</p></div></div>{/if}{#if form?.message}<p class="form-alert" role="alert">{form.message}</p>{/if}
  {#if data.accounts.length}<section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">New transfer</p><h2>Deposit or withdraw capital</h2><p class="section-caption">Use a personal wallet in the same currency. Transfers update wallet balances but are not income or spending.</p></div></div><form method="POST" action="?/cashMovement" class="feature-form investment-form" use:enhance={handleInvestmentSubmit}><label>Investment account<select name="investment_account_id" required>{#each data.accounts as account}<option value={account.id}>{account.name} · {account.currency === 'USD' ? 'USD' : 'ZiG'}</option>{/each}</select></label><label>Movement<select name="kind"><option value="deposit">Deposit to investment</option><option value="withdrawal">Withdraw to personal wallet</option></select></label><label>Personal wallet<select name="wallet_account_id" required>{#each data.wallets as wallet}<option value={wallet.id}>{wallet.currency === 'USD' ? 'USD' : 'ZiG'} · {wallet.wallet_group?.name ?? 'Wallet'}{wallet.channel ? ` · ${wallet.channel}` : ''}</option>{/each}</select></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required/></label><label>Date<input name="occurred_on" type="date" value={data.today} required/></label><label class="form-wide">Note<input name="description" maxlength="240" placeholder="Optional transfer note"/></label><div class="form-wide form-footer"><p>Withdrawals cannot exceed the recorded investment balance.</p><button class="primary-button" type="submit"><ArrowLeftRight size={16}/> Record transfer</button></div></form></section>
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Transfer history</p><h2>Deposits and withdrawals</h2></div></div><div class="investment-activity-list">{#each data.movements as movement}<div class="investment-activity-row"><span class="investment-activity-icon">{#if movement.kind === 'deposit'}<ArrowUpRight size={16}/>{:else}<ArrowDownLeft size={16}/>{/if}</span><div class="investment-activity-main"><strong>{movement.kind === 'deposit' ? 'Deposit to' : 'Withdrawal from'} {accountName(movement.investment_account_id)}</strong><span>{new Date(movement.occurred_at).toLocaleDateString()} · {movement.description || 'Investment transfer'}</span></div><strong class="investment-activity-amount">{money(movement.amount, accountCurrency(movement.investment_account_id))}</strong></div>{:else}<p class="investment-table-empty">No investment transfers yet.</p>{/each}</div></section>
  {:else}<section class="investment-empty"><span class="investment-icon"><ArrowLeftRight size={20}/></span><div><h2>Create an investment account before transferring capital</h2><p>Set up the investment account first so deposits and withdrawals have a destination.</p><a class="primary-button compact-button" href="/investments/accounts">Open Accounts</a></div></section>{/if}
  <footer class="dashboard-footer"><span>Personal wallet balances reflect these movements.</span><span>Capital transfers are excluded from household income and spending.</span></footer>
</div></main><nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a class="mobile-nav-active" href="/investments"><TrendingUp size={18}/><span>Investments</span></a><a href="/budgets"><Target size={18}/><span>Budgets</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav></div>
