<script lang="ts">
  import { ArrowLeftRight, BarChart3, LayoutDashboard, LogOut, Settings2, WalletCards, TrendingUp, TrendingDown } from 'lucide-svelte';
  import { decimalToMinorUnits, formatMoney } from '$lib/finance';
  import type { Currency } from '$lib/types/finance';
  import type { PageData } from './$types';
  let { data }: { data: PageData } = $props();
  let movementMode = $state<'both' | 'income' | 'spending'>('both');
  const money = (value: string, currency: Currency) => formatMoney(decimalToMinorUnits(value), currency);
  const movementTotal = (field: 'income' | 'spending', currency: Currency) => data.months.reduce((sum, month) => sum + decimalToMinorUnits(month[currency][field]), 0n);
  const max = (currency: Currency) => Math.max(1, ...data.months.flatMap((month) => [movementMode !== 'spending' ? Number(month[currency].income) : 0, movementMode !== 'income' ? Number(month[currency].spending) : 0]));
  const height = (value: string, currency: Currency) => `${Number(value) === 0 ? 0 : Math.max(3, Number(value) / max(currency) * 100)}%`;
  const halfMax = (currency: Currency) => String(Math.round(max(currency) * 50) / 100);
</script>
<svelte:head><title>Insights — Budget</title></svelte:head>
<div class="app-frame"><aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link" href="/budgets"><WalletCards size={18}/> Budgets</a><a class="side-link active" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
<main class="main-area"><header class="topbar"><div><p class="date-label">Patterns at a glance</p><p class="topbar-title">Insights</p></div></header><div class="content-wrap"><section class="welcome-row"><div><p class="eyebrow">Your trends</p><h1>Understand where it <span class="accent-period">goes.</span></h1><p class="welcome-copy">Compare monthly income and spending while keeping USD and ZiG separate.</p></div><div class="currency-note">Last 6 months</div></section>
{#if data.loadError}<div class="setup-banner"><div><strong>Database setup needed</strong><p>{data.loadError}. Run the setup SQL in Supabase, then refresh.</p></div></div>{/if}
<section class="overview-metrics insight-balance-metrics" aria-label="Current wallet balances"><article class="overview-metric balance-metric"><div class="metric-heading"><span class="metric-icon"><WalletCards size={17}/></span><span>Current USD balance</span></div><p class="metric-caption">Across active wallets, including opening balances</p><strong class="insight-balance-value">{money(data.balances.USD, 'USD')}</strong></article><article class="overview-metric balance-metric"><div class="metric-heading"><span class="metric-icon"><WalletCards size={17}/></span><span>Current ZiG balance</span></div><p class="metric-caption">Across active wallets, including opening balances</p><strong class="insight-balance-value">{money(data.balances.ZIG, 'ZIG')}</strong></article></section>
<section class="overview-metrics insight-flow-metrics" aria-label="Income and spending in the last six months">{#each ['income', 'spending'] as field}<article class="overview-metric"><div class="metric-heading"><span class="metric-icon" class:income-metric-icon={field === 'income'} class:spend-metric-icon={field === 'spending'}>{#if field === 'income'}<TrendingUp size={17}/>{:else}<TrendingDown size={17}/>{/if}</span><span>{field === 'income' ? 'Income received' : 'Spent, including transfer fees'} · 6 months</span></div><p class="metric-caption">Combined by currency, never converted</p><div class="metric-currency-pair"><div><span class="currency-badge">USD</span><strong>{formatMoney(movementTotal(field as 'income' | 'spending', 'USD'), 'USD')}</strong></div><div><span class="currency-badge zig-badge">ZiG</span><strong>{formatMoney(movementTotal(field as 'income' | 'spending', 'ZIG'), 'ZIG')}</strong></div></div></article>{/each}</section>
<section class="section-block"><div class="section-heading movement-heading"><div><p class="eyebrow">Income and spending</p><h2>Monthly movement</h2><p class="section-caption">Compare each currency on its own scale.</p></div><div class="chart-toggle" role="group" aria-label="Monthly chart view"><button type="button" class:active={movementMode === 'both'} aria-pressed={movementMode === 'both'} onclick={() => movementMode = 'both'}>Both</button><button type="button" class:active={movementMode === 'income'} aria-pressed={movementMode === 'income'} onclick={() => movementMode = 'income'}>Income</button><button type="button" class:active={movementMode === 'spending'} aria-pressed={movementMode === 'spending'} onclick={() => movementMode = 'spending'}>Spending</button></div></div>{#if !data.hasMovement}<div class="analytics-empty-note"><strong>No income or spending recorded in these six months yet.</strong><span>Opening balances appear above and aren’t counted as monthly movement. Record a transaction to start building your trends.</span><a href="/transactions">Add a transaction →</a></div>{/if}<div class="movement-charts">{#each ['USD', 'ZIG'] as currency}<article class="movement-chart"><header><span class="currency-badge" class:zig-badge={currency === 'ZIG'}>{currency === 'USD' ? 'USD' : 'ZiG'}</span><strong>{currency === 'USD' ? 'US dollar' : 'Zimbabwe Gold'}</strong></header><div class="bar-chart" role="img" aria-label={`${currency} monthly ${movementMode === 'both' ? 'income and spending' : movementMode}`}><div class="chart-y-labels"><span>{money(String(max(currency as Currency)), currency as Currency)}</span><span>{money(halfMax(currency as Currency), currency as Currency)}</span><span>0</span></div><div class="chart-plot">{#each data.months as month}<div class="chart-month"><div class="chart-bars">{#if movementMode !== 'spending'}<span class="chart-column income-column" style={`height:${height(month[currency as Currency].income, currency as Currency)}`} title={`Income ${money(month[currency as Currency].income, currency as Currency)}`}></span>{/if}{#if movementMode !== 'income'}<span class="chart-column spending-column" style={`height:${height(month[currency as Currency].spending, currency as Currency)}`} title={`Spending ${money(month[currency as Currency].spending, currency as Currency)}`}></span>{/if}</div><span class="chart-month-label">{month.label}</span></div>{/each}</div></div></article>{/each}</div><div class="chart-legend"><span><i class="legend-income"></i>Income</span><span><i class="legend-spend"></i>Spending and transfer fees</span></div></section>
<div class="insight-columns"><section class="section-block"><div class="section-heading"><div><p class="eyebrow">Current month</p><h2>Top categories</h2></div></div>{#if data.topCategories.length}<div class="settings-list">{#each data.topCategories as category}<div class="settings-row"><div><strong>{category.name}</strong><span>{category.currency} · Spending</span></div><strong>{money(category.amount, category.currency as Currency)}</strong></div>{/each}</div>{:else}<div class="empty-card compact-empty"><h3>No spending patterns yet</h3><p>Add transactions to see your top categories.</p></div>{/if}</section>
<section class="section-block"><div class="section-heading"><div><p class="eyebrow">By wallet</p><h2>Income and outflow</h2></div></div>{#if data.wallets.length}<div class="settings-list">{#each data.wallets as wallet}<div class="settings-row wallet-insight-row"><div><strong>{wallet.group}</strong><span>{wallet.currency} · In {money(wallet.income, wallet.currency as Currency)}</span></div><span class="wallet-outflow">Out {money(wallet.spending, wallet.currency as Currency)}</span></div>{/each}</div>{:else}<div class="empty-card compact-empty"><h3>No wallet activity yet</h3><p>Wallet summaries appear after transactions are added.</p></div>{/if}</section></div>
<footer class="dashboard-footer"><span>Currency amounts are never combined.</span><span>Monthly view starts {new Date(`${data.periodStart}T00:00:00`).toLocaleDateString('en', { month: 'long', year: 'numeric' })}.</span></footer></div></main>
<nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a href="/budgets"><WalletCards size={18}/><span>Budgets</span></a><a class="mobile-nav-active" href="/insights"><BarChart3 size={18}/><span>Insights</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav></div>
