<script lang="ts">
  import { ArrowLeftRight, BarChart3, LayoutDashboard, LogOut, Settings2, Target, TrendingUp, WalletCards } from 'lucide-svelte';
  import InvestmentNav from '$lib/components/InvestmentNav.svelte';
  import type { ActionData, PageData } from './$types';
  let { data, form }: { data: PageData; form: ActionData } = $props();
  const money = (value: number | string, currency: string, unit = false) => `${currency === 'USD' ? '$' : 'ZiG '}${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: unit ? 6 : 2 })}`;
  const quantity = (value: number | string) => Number(value).toLocaleString('en-US', { maximumFractionDigits: 6 });
  const stocksAccounts = data.accounts.filter((account) => account.kind === 'stocks');
  const counters = data.counters;
</script>
<svelte:head><title>Stocks — Budget</title></svelte:head>
<div class="app-frame"><aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link active" href="/investments"><TrendingUp size={18}/> Investments</a><a class="side-link" href="/budgets"><Target size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
<main class="main-area"><header class="topbar"><div><p class="date-label">VFEX counters and holdings</p><p class="topbar-title">Stocks</p></div></header><InvestmentNav active="stocks"/><div class="content-wrap investment-content">
  <section class="welcome-row"><div><p class="eyebrow">Long-term holdings</p><h1>Stocks<span class="accent-period">.</span></h1><p class="welcome-copy">Keep individual purchase lots, record charges, and update each counter’s daily close.</p></div></section>
  {#if data.loadError}<div class="setup-banner"><div><strong>Investment data is not ready</strong><p>{data.loadError}. Apply the investments migration in Supabase, then refresh.</p></div></div>{/if}{#if form?.message}<p class="form-alert" role="alert">{form.message}</p>{/if}
  {#if stocksAccounts.length}
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Portfolio counters</p><h2>Add a counter or import an existing holding</h2><p class="section-caption">Enter your existing share quantity, original buy price, and current price here. This opening lot will not deduct cash from your brokerage or personal wallet.</p></div></div><form method="POST" action="?/addCounter" class="feature-form investment-form">
      <label>Stocks account<select name="investment_account_id" required>{#each stocksAccounts as account}<option value={account.id}>{account.name} · {account.currency === 'USD' ? 'USD' : 'ZiG'}</option>{/each}</select></label><label>Counter / ticker<input name="ticker" maxlength="20" placeholder="Counter ticker" required/></label><label>Company name<input name="company_name" maxlength="100" placeholder="Company name" required/></label><label>Existing shares<input name="opening_quantity" type="number" min="0" step="0.000001" value="0" inputmode="decimal"/></label><label>Original buy price per share<input name="opening_buy_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" placeholder="Required when importing shares"/></label><label>Charges on those shares<input name="opening_fees" type="number" min="0" step="0.01" value="0" inputmode="decimal"/></label><label>Current price per share<input name="current_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" placeholder="Required when importing shares"/></label><label>Purchase date<input name="acquired_on" type="date" value={data.today} required/></label><label>Current price date<input name="price_date" type="date" value={data.today} required/></label><div class="form-wide form-footer"><p>For multiple historical purchase prices, import the first lot here and add each later purchase below.</p><button class="primary-button" type="submit">Add counter and holding</button></div>
    </form></section>
    {#if counters.length}
      <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Import existing shares</p><h2>Add another purchase lot</h2><p class="section-caption">Use this for an additional historical lot you already own. It records the old buy price and today’s reference price without changing brokerage cash.</p></div></div><form method="POST" action="?/openingLot" class="feature-form investment-form"><label>Counter<select name="counter_id" required>{#each counters as counter}<option value={counter.id}>{counter.ticker} · {counter.company_name}</option>{/each}</select></label><label>Shares in this lot<input name="quantity" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Original buy price per share<input name="unit_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Charges on this lot<input name="fees" type="number" min="0" step="0.01" value="0" inputmode="decimal"/></label><label>Purchase date<input name="occurred_on" type="date" value={data.today} required/></label><label>Current price per share<input name="current_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Current price date<input name="price_date" type="date" value={data.today} required/></label><div class="form-wide form-footer"><p>Imported lots are kept separate so each buy price remains visible.</p><button class="primary-button" type="submit">Import purchase lot</button></div></form></section>
      <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Trade activity</p><h2>Record a buy or sell</h2><p class="section-caption">Sells consume the oldest available purchase lots first. Buy charges add to cost; sell charges reduce proceeds.</p></div></div><form method="POST" action="?/trade" class="feature-form investment-form"><label>Counter<select name="counter_id" required>{#each counters as counter}<option value={counter.id}>{counter.ticker} · {counter.company_name}</option>{/each}</select></label><label>Trade<select name="kind"><option value="buy">Buy</option><option value="sell">Sell · FIFO</option></select></label><label>Share quantity<input name="quantity" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Price per share<input name="unit_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Total charges<input name="fees" type="number" min="0" step="0.01" value="0" inputmode="decimal"/></label><label>Date<input name="occurred_on" type="date" value={data.today} required/></label><label class="form-wide">Note<input name="description" maxlength="240" placeholder="Optional trade note"/></label><div class="form-wide form-footer"><p>Buys use available brokerage cash.</p><button class="primary-button" type="submit">Save trade</button></div></form></section>
      <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Daily market close</p><h2>Update a closing price</h2><p class="section-caption">Market value is calculated as shares held × closing price.</p></div></div><form method="POST" action="?/price" class="feature-form investment-form compact-investment-form"><label>Counter<select name="counter_id" required>{#each counters as counter}<option value={counter.id}>{counter.ticker} · {counter.company_name}</option>{/each}</select></label><label>Closing price per share<input name="closing_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Date<input name="price_date" type="date" value={data.today} required/></label><div class="form-footer"><button class="primary-button" type="submit">Save price</button></div></form></section>
    {/if}
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Current holdings</p><h2>Positions by counter</h2></div></div><div class="investment-table-wrap"><table class="investment-table"><thead><tr><th>Counter</th><th>Shares</th><th>Avg. cost / share</th><th>Latest close</th><th>Market value</th><th>Unrealized P/L</th></tr></thead><tbody>{#each data.positions.filter((position) => position.shares > 0) as position}<tr><td><strong>{position.ticker}</strong><small>{position.company_name}</small></td><td>{quantity(position.shares)}</td><td>{money(position.shares ? position.costBasis / position.shares : 0, data.accounts.find((account) => account.id === position.investment_account_id)?.currency ?? 'USD', true)}</td><td>{position.closingPrice ? money(position.closingPrice, data.accounts.find((account) => account.id === position.investment_account_id)?.currency ?? 'USD', true) : '—'}<small>{position.quoteDate ?? 'No price recorded'}</small></td><td>{position.marketValue === null ? '—' : money(position.marketValue, data.accounts.find((account) => account.id === position.investment_account_id)?.currency ?? 'USD')}</td><td class:gain={position.unrealized !== null && position.unrealized >= 0} class:loss={position.unrealized !== null && position.unrealized < 0}>{position.unrealized === null ? '—' : money(position.unrealized, data.accounts.find((account) => account.id === position.investment_account_id)?.currency ?? 'USD')}</td></tr>{/each}</tbody></table>{#if !data.positions.some((position) => position.shares > 0)}<p class="investment-table-empty">Record a buy to see your current holdings.</p>{/if}</div></section>
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Purchase and sale lots</p><h2>Recent stock trades</h2></div></div><div class="investment-activity-list">{#each data.trades.slice(0, 20) as trade}<div class="investment-activity-row"><span class="investment-activity-icon"><TrendingUp size={16}/></span><div class="investment-activity-main"><strong>{trade.kind === 'opening' ? 'Existing position' : trade.kind === 'buy' ? 'Buy' : 'Sell'} · {counters.find((counter) => counter.id === trade.counter_id)?.ticker ?? 'Counter'} · {quantity(trade.quantity)} shares</strong><span>{new Date(trade.occurred_at).toLocaleDateString()} · {trade.kind === 'sell' ? `FIFO realized P/L ${money(Number(trade.realized_profit ?? 0), data.accounts.find((account) => account.id === trade.investment_account_id)?.currency ?? 'USD')}` : trade.description || 'Purchase lot'}{Number(trade.fees) ? ` · charges ${money(trade.fees, data.accounts.find((account) => account.id === trade.investment_account_id)?.currency ?? 'USD')}` : ''}</span></div><strong class="investment-activity-amount">{money(Number(trade.quantity) * Number(trade.unit_price), data.accounts.find((account) => account.id === trade.investment_account_id)?.currency ?? 'USD')}</strong></div>{:else}<p class="investment-table-empty">No trades recorded yet.</p>{/each}</div></section>
  {:else}<section class="investment-empty"><span class="investment-icon"><TrendingUp size={20}/></span><div><h2>Create a stocks account first</h2><p>Add your VFEX brokerage on the Accounts page, then add company counters here.</p><a class="primary-button compact-button" href="/investments/accounts">Open Accounts</a></div></section>{/if}
  <footer class="dashboard-footer"><span>Trade amounts stay in the brokerage currency.</span><span>Daily closing prices are entered manually.</span></footer>
</div></main><nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a class="mobile-nav-active" href="/investments"><TrendingUp size={18}/><span>Investments</span></a><a href="/budgets"><Target size={18}/><span>Budgets</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav></div>
