<script lang="ts">
  import { ArrowLeftRight, BarChart3, LayoutDashboard, LogOut, Settings2, Target, TrendingUp, WalletCards } from 'lucide-svelte';
  import InvestmentNav from '$lib/components/InvestmentNav.svelte';
  import { enhance } from '$app/forms';
  import { handleInvestmentSubmit } from '$lib/investments/feedback';
  import type { ActionData, PageData } from './$types';
  let { data, form }: { data: PageData; form: ActionData } = $props();
  let mode = $state<'existing' | 'new'>('existing');
  let fundingSource = $state<'brokerage' | 'wallet'>('brokerage');
  let purchaseAccountId = $state('');
  const money = (value: number | string, currency: string, unit = false) => `${currency === 'USD' ? '$' : 'ZiG '}${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: unit ? 6 : 2 })}`;
  const quantity = (value: number | string) => Number(value).toLocaleString('en-US', { maximumFractionDigits: 6 });
  const stocksAccounts = $derived(data.accounts.filter((account: any) => account.kind === 'stocks'));
  const counters = $derived(data.counters);
  const purchaseAccount = $derived(stocksAccounts.find((account: any) => account.id === purchaseAccountId) ?? stocksAccounts[0]);
  const purchaseWallets = $derived(data.wallets.filter((wallet: any) => wallet.currency === purchaseAccount?.currency));
  $effect(() => { if (!purchaseAccountId && stocksAccounts.length) purchaseAccountId = stocksAccounts[0].id; });
</script>
<svelte:head><title>Stocks — Budget</title></svelte:head>
<div class="app-frame"><aside class="sidebar"><a class="brand" href="/dashboard"><span class="brand-mark"><WalletCards size={21}/></span><span>Budget</span></a><div class="sidebar-label">Workspace</div><a class="side-link" href="/dashboard"><LayoutDashboard size={18}/> Overview</a><div class="sidebar-label side-label-spaced">Your money</div><a class="side-link" href="/wallets"><WalletCards size={18}/> Wallets</a><a class="side-link" href="/transactions"><ArrowLeftRight size={18}/> Transactions</a><a class="side-link active" href="/investments"><TrendingUp size={18}/> Investments</a><a class="side-link" href="/budgets"><Target size={18}/> Budgets</a><a class="side-link" href="/insights"><BarChart3 size={18}/> Insights</a><div class="sidebar-bottom"><a class="side-link" href="/settings"><Settings2 size={18}/> Settings</a><form method="POST" action="/logout"><button class="side-link" type="submit"><LogOut size={18}/> Sign out</button></form></div></aside>
<main class="main-area"><header class="topbar"><div><p class="date-label">VFEX counters and holdings</p><p class="topbar-title">Stocks</p></div></header><InvestmentNav active="stocks"/><div class="content-wrap investment-content">
  <section class="welcome-row"><div><p class="eyebrow">Long-term holdings</p><h1>Stocks<span class="accent-period">.</span></h1><p class="welcome-copy">Import shares you already own or record a new purchase from a personal wallet.</p></div></section>
  {#if data.loadError}<div class="setup-banner"><div><strong>Investment data is not ready</strong><p>{data.loadError}. Apply migrations through 0004 in Supabase, then refresh.</p></div></div>{/if}
  {#if form?.message}<p class="form-alert" role="alert">{form.message}</p>{/if}
  {#if stocksAccounts.length}
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Add an investment</p><h2>{mode === 'existing' ? 'Import existing shares' : 'Record a new stock purchase'}</h2><p class="section-caption">{mode === 'existing' ? 'Record shares already held. This does not change any personal wallet.' : 'The selected wallet will be debited for share value and transfer charges together.'}</p></div></div>
      <div class="investment-mode-switch" role="group" aria-label="Choose stock entry type"><button type="button" class:active={mode === 'existing'} aria-pressed={mode === 'existing'} onclick={() => mode = 'existing'}>Existing holding</button><button type="button" class:active={mode === 'new'} aria-pressed={mode === 'new'} onclick={() => mode = 'new'}>New purchase</button></div>
      {#if mode === 'existing'}
        <form method="POST" action="?/importExisting" class="feature-form investment-form" use:enhance={handleInvestmentSubmit}>
          <label>Stocks account<select name="investment_account_id" required>{#each stocksAccounts as account}<option value={account.id}>{account.name} · {account.currency === 'USD' ? 'USD' : 'ZiG'}</option>{/each}</select></label>
          <label>Counter / company name<input name="counter_name" maxlength="100" placeholder="e.g. Delta Corporation" required/></label>
          <label>Shares you already own<input name="quantity" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label>
          <label>Original buying price per share<input name="unit_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label>
          <label>Charges paid (optional)<input name="fees" type="number" min="0" step="0.01" value="0" inputmode="decimal"/></label>
          <label>Purchase date<input name="occurred_on" type="date" value={data.today} required/></label>
          <div class="form-wide form-footer"><p>This keeps the original cost as a separate lot and leaves your wallets unchanged.</p><button class="primary-button" type="submit">Import existing shares</button></div>
        </form>
      {:else}
        <form method="POST" action="?/newPurchase" class="feature-form investment-form" use:enhance={handleInvestmentSubmit}>
          <label>Stocks account<select name="investment_account_id" bind:value={purchaseAccountId} required>{#each stocksAccounts as account}<option value={account.id}>{account.name} · {account.currency === 'USD' ? 'USD' : 'ZiG'} · brokerage cash {money(account.currentCash, account.currency)}</option>{/each}</select></label>
          <label>Payment source<select name="funding_source" bind:value={fundingSource} required><option value="brokerage">Cash already in this brokerage</option><option value="wallet">Debit a personal wallet directly</option></select></label>
          {#if fundingSource === 'wallet'}<label>Pay from wallet<select name="wallet_account_id" required>{#each purchaseWallets as wallet}<option value={wallet.id}>{wallet.wallet_group?.name ?? 'Wallet'}{wallet.channel ? ` · ${wallet.channel}` : ''} · {wallet.currency === 'USD' ? 'USD' : 'ZiG'}</option>{:else}<option value="">No active matching wallet</option>{/each}</select></label>{/if}
          <label>Counter / company name<input name="counter_name" maxlength="100" placeholder="e.g. Delta Corporation" required/></label>
          <label>Shares purchased<input name="quantity" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label>
          <label>Buying price per share<input name="unit_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label>
          <label>Transfer charges<input name="fees" type="number" min="0" step="0.01" value="0" inputmode="decimal" required/></label>
          <label>Purchase date<input name="occurred_on" type="date" value={data.today} required/></label>
          <label class="form-wide">Note<input name="description" maxlength="240" placeholder="Optional purchase note"/></label>
          <div class="form-wide form-footer"><p>{fundingSource === 'brokerage' ? 'The total cost and charges will be deducted from this brokerage account’s available cash.' : 'Wallet debit = shares × buying price + transfer charges. The transfer is not household spending.'}</p><button class="primary-button" type="submit" disabled={fundingSource === 'wallet' && !purchaseWallets.length}>Record new purchase</button></div>
        </form>
      {/if}
    </section>
    {#if counters.length}
      <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Trade activity</p><h2>Record a sale or brokerage funded trade</h2><p class="section-caption">Use wallet funded purchases above to record new purchases from personal funds. This form uses brokerage cash already in the investment account.</p></div></div><form method="POST" action="?/trade" class="feature-form investment-form" use:enhance={handleInvestmentSubmit}><label>Counter<select name="counter_id" required>{#each counters as counter}<option value={counter.id}>{counter.ticker} · {counter.company_name}</option>{/each}</select></label><label>Trade<select name="kind"><option value="sell">Sell · FIFO</option><option value="buy">Buy from brokerage cash</option></select></label><label>Share quantity<input name="quantity" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Price per share<input name="unit_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Total charges<input name="fees" type="number" min="0" step="0.01" value="0" inputmode="decimal"/></label><label>Date<input name="occurred_on" type="date" value={data.today} required/></label><label class="form-wide">Note<input name="description" maxlength="240" placeholder="Optional trade note"/></label><div class="form-wide form-footer"><p>Buys use available brokerage cash.</p><button class="primary-button" type="submit">Save trade</button></div></form></section>
    {/if}
    {#if counters.length}<section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Daily market close</p><h2>Update a closing price</h2><p class="section-caption">Current market value and unrealized gain use the latest price entered here.</p></div></div><form method="POST" action="?/price" class="feature-form investment-form compact-investment-form" use:enhance={handleInvestmentSubmit}><label>Counter<select name="counter_id" required>{#each counters as counter}<option value={counter.id}>{counter.ticker} · {counter.company_name}</option>{/each}</select></label><label>Closing price per share<input name="closing_price" type="number" min="0.000001" step="0.000001" inputmode="decimal" required/></label><label>Date<input name="price_date" type="date" value={data.today} required/></label><div class="form-footer"><button class="primary-button" type="submit">Save price</button></div></form></section>{/if}
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Current holdings</p><h2>Positions by counter</h2></div></div><div class="investment-table-wrap"><table class="investment-table"><thead><tr><th>Counter</th><th>Shares</th><th>Avg. cost / share</th><th>Latest close</th><th>Market value</th><th>Unrealized P/L</th></tr></thead><tbody>{#each data.positions.filter((position: any) => position.shares > 0) as position}<tr><td><strong>{position.ticker}</strong><small>{position.company_name}</small></td><td>{quantity(position.shares)}</td><td>{money(position.shares ? position.costBasis / position.shares : 0, data.accounts.find((account: any) => account.id === position.investment_account_id)?.currency ?? 'USD', true)}</td><td>{position.closingPrice ? money(position.closingPrice, data.accounts.find((account: any) => account.id === position.investment_account_id)?.currency ?? 'USD', true) : '—'}<small>{position.quoteDate ?? 'No close recorded'}</small></td><td>{position.marketValue === null ? '—' : money(position.marketValue, data.accounts.find((account: any) => account.id === position.investment_account_id)?.currency ?? 'USD')}</td><td class:gain={position.unrealized !== null && position.unrealized >= 0} class:loss={position.unrealized !== null && position.unrealized < 0}>{position.unrealized === null ? '—' : money(position.unrealized, data.accounts.find((account: any) => account.id === position.investment_account_id)?.currency ?? 'USD')}</td></tr>{/each}</tbody></table>{#if !data.positions.some((position: any) => position.shares > 0)}<p class="investment-table-empty">Import your existing shares or record a new purchase to see holdings here.</p>{/if}</div></section>
    <section class="section-block investment-section"><div class="section-heading"><div><p class="eyebrow">Purchase and sale lots</p><h2>Recent stock activity</h2></div></div><div class="investment-activity-list">{#each data.trades.slice(0, 20) as trade}<div class="investment-activity-row"><span class="investment-activity-icon"><TrendingUp size={16}/></span><div class="investment-activity-main"><strong>{trade.kind === 'opening' ? 'Existing position' : trade.kind === 'buy' ? 'Buy' : 'Sell'} · {counters.find((counter: any) => counter.id === trade.counter_id)?.ticker ?? 'Counter'} · {quantity(trade.quantity)} shares</strong><span>{new Date(trade.occurred_at).toLocaleDateString()} · {trade.kind === 'sell' ? `FIFO realized P/L ${money(Number(trade.realized_profit ?? 0), data.accounts.find((account: any) => account.id === trade.investment_account_id)?.currency ?? 'USD')}` : trade.description || 'Purchase lot'}{Number(trade.fees) ? ` · charges ${money(trade.fees, data.accounts.find((account: any) => account.id === trade.investment_account_id)?.currency ?? 'USD')}` : ''}</span></div><strong class="investment-activity-amount">{money(Number(trade.quantity) * Number(trade.unit_price), data.accounts.find((account: any) => account.id === trade.investment_account_id)?.currency ?? 'USD')}</strong></div>{:else}<p class="investment-table-empty">No stock activity recorded yet.</p>{/each}</div></section>
  {:else}<section class="investment-empty"><span class="investment-icon"><TrendingUp size={20}/></span><div><h2>Create a stocks account first</h2><p>Add your VFEX brokerage on the Accounts page, then record your holdings here.</p><a class="primary-button compact-button" href="/investments/accounts">Open Accounts</a></div></section>{/if}
  <footer class="dashboard-footer"><span>Stock values stay in brokerage currency.</span><span>Enter closing prices manually for daily performance analysis.</span></footer>
</div></main><nav class="mobile-nav" aria-label="Main navigation"><a href="/dashboard"><LayoutDashboard size={18}/><span>Overview</span></a><a href="/wallets"><WalletCards size={18}/><span>Wallets</span></a><a href="/transactions"><ArrowLeftRight size={18}/><span>Activity</span></a><a class="mobile-nav-active" href="/investments"><TrendingUp size={18}/><span>Investments</span></a><a href="/budgets"><Target size={18}/><span>Budgets</span></a><a href="/settings"><Settings2 size={18}/><span>Settings</span></a></nav></div>
